### ISSUE TITLE
Homepage broken (k3s.io)

### ISSUE THREAD

**Issue by septatrix** [k3s-io/k3s-io.github.io#3]
**Environmental Info:**
K3s Version: n/a

Node(s) CPU architecture, OS, and Version: 
n/a

Cluster Configuration:
n/a

**Describe the bug:**
The homepage is broken as the stylesheet (<https://k3s.io/sass/main.min.css?1634021040>) is not found (error 404).

**Steps To Reproduce:**
* Open <https://www.k3s.io/>

**Expected behavior:**
The site should show up with proper styles loaded.

**Actual behavior:**
The layout and styles are completely broken.

**Comment by sndsgd** [comment]
```
$ dig k3s.io +short
185.199.108.153
185.199.110.153
185.199.111.153
185.199.109.153
```
```
$ dig www.k3s.io +short
104.26.15.42
172.67.69.209
104.26.14.42
```
looks like `www.k3s.io` is pointing to cloudflare, and `k3s.io` is pointing to github pages :eyes:

**Comment by sndsgd** [comment]
@cwayne18 looks like this has been addressed :eyes:

**Comment by cwayne18** [comment]
Yes sorry I should have closed this, we've fixed the issue, thanks for reporting!
